version: '3.8'

services:
  remna-bot:
    build: .
    container_name: remna-bot-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
